const express = require("express");
const Database = require("better-sqlite3");
const path = require("path");
const fs = require("fs");

const app = express();
const PORT = Number(process.env.PORT || 3000);
const VERIFY_TOKEN = process.env.VERIFY_TOKEN || "change-this-webhook-token";
const dataDir = path.join(__dirname, "..", "data");
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });
const db = new Database(path.join(dataDir, "maseray.db"));
db.pragma("journal_mode = WAL");
db.exec(`CREATE TABLE IF NOT EXISTS members (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT NOT NULL UNIQUE,membership_number TEXT NOT NULL UNIQUE,monthly_contribution REAL NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS contributions (id INTEGER PRIMARY KEY AUTOINCREMENT,member_id INTEGER NOT NULL,contribution_month TEXT NOT NULL,amount REAL NOT NULL,status TEXT NOT NULL DEFAULT 'unpaid',payment_reference TEXT,paid_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(member_id, contribution_month),FOREIGN KEY(member_id) REFERENCES members(id));`);
if (db.prepare("SELECT COUNT(*) c FROM members").get().c === 0) db.prepare("INSERT INTO members(name,phone,membership_number,monthly_contribution) VALUES(?,?,?,?)").run("Demo Member","23200000000","MTB-001",100);
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(express.static(path.join(__dirname,"..","public")));
const cleanPhone = (phone="") => String(phone).replace(/\D/g, "");
const memberByPhone = phone => db.prepare("SELECT * FROM members WHERE phone=? AND active=1").get(cleanPhone(phone));
app.get("/api/health", (req,res)=>res.json({ok:true,service:"maseray-whatsapp-webhook"}));
app.get("/api/members", (req,res)=>res.json(db.prepare(`SELECT m.*,COALESCE(SUM(CASE WHEN c.status='paid' THEN c.amount ELSE 0 END),0) total_paid,COUNT(c.id) contribution_count FROM members m LEFT JOIN contributions c ON c.member_id=m.id GROUP BY m.id ORDER BY m.name COLLATE NOCASE`).all()));
app.post("/api/members", (req,res)=>{try{const {name,phone,membership_number,monthly_contribution}=req.body;if(!name||!phone||!membership_number)return res.status(400).json({error:"Name, phone and membership number are required."});const r=db.prepare("INSERT INTO members(name,phone,membership_number,monthly_contribution) VALUES(?,?,?,?)").run(name.trim(),cleanPhone(phone),membership_number.trim(),Number(monthly_contribution||0));res.json(db.prepare("SELECT * FROM members WHERE id=?").get(r.lastInsertRowid));}catch(e){res.status(400).json({error:"Phone or membership number already exists."})}});
app.put("/api/members/:id",(req,res)=>{try{const {name,phone,membership_number,monthly_contribution,active}=req.body;db.prepare("UPDATE members SET name=?,phone=?,membership_number=?,monthly_contribution=?,active=? WHERE id=?").run(String(name||"").trim(),cleanPhone(phone),String(membership_number||"").trim(),Number(monthly_contribution||0),active===false?0:1,Number(req.params.id));res.json(db.prepare("SELECT * FROM members WHERE id=?").get(Number(req.params.id)));}catch(e){res.status(400).json({error:"Could not update member."})}});
app.delete("/api/members/:id",(req,res)=>{db.prepare("UPDATE members SET active=0 WHERE id=?").run(Number(req.params.id));res.json({ok:true})});
app.get("/api/contributions",(req,res)=>res.json(db.prepare("SELECT c.*,m.name,m.phone,m.membership_number FROM contributions c JOIN members m ON m.id=c.member_id ORDER BY c.contribution_month DESC,m.name COLLATE NOCASE").all()));
app.post("/api/contributions",(req,res)=>{try{const {member_id,contribution_month,amount,status,payment_reference}=req.body;if(!member_id||!contribution_month||!amount)return res.status(400).json({error:"Member, month and amount are required."});const paid=status==="paid";db.prepare(`INSERT INTO contributions(member_id,contribution_month,amount,status,payment_reference,paid_at) VALUES(?,?,?,?,?,?) ON CONFLICT(member_id,contribution_month) DO UPDATE SET amount=excluded.amount,status=excluded.status,payment_reference=excluded.payment_reference,paid_at=excluded.paid_at`).run(Number(member_id),contribution_month,Number(amount),paid?"paid":"unpaid",payment_reference||null,paid?new Date().toISOString():null);res.json({ok:true});}catch(e){res.status(400).json({error:"Could not save contribution."})}});
app.get("/api/member/lookup",(req,res)=>{const member=memberByPhone(req.query.phone);if(!member)return res.status(404).json({error:"Member not found."});const history=db.prepare("SELECT contribution_month,amount,status,payment_reference,paid_at FROM contributions WHERE member_id=? ORDER BY contribution_month DESC").all(member.id);res.json({member,history})});
app.get("/api/reports/summary",(req,res)=>res.json({active_members:db.prepare("SELECT COUNT(*) c FROM members WHERE active=1").get().c,total_paid:db.prepare("SELECT COALESCE(SUM(amount),0) total FROM contributions WHERE status='paid'").get().total,total_unpaid:db.prepare("SELECT COALESCE(SUM(amount),0) total FROM contributions WHERE status='unpaid'").get().total}));
app.get("/webhook/whatsapp",(req,res)=>{if(req.query["hub.mode"]==="subscribe"&&req.query["hub.verify_token"]===VERIFY_TOKEN)return res.status(200).send(req.query["hub.challenge"]);res.sendStatus(403)});
app.post("/webhook/whatsapp",(req,res)=>{res.sendStatus(200);try{const value=req.body?.entry?.[0]?.changes?.[0]?.value;const message=value?.messages?.[0];if(!message)return;const phone=cleanPhone(message.from);const member=memberByPhone(phone);console.log("WhatsApp message",{phone,memberName:member?.name||null,type:message.type});}catch(e){console.error("Webhook error",e)}});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"..","public","index.html")));
app.listen(PORT,"0.0.0.0",()=>console.log(`Maseray Temne Blogger running on port ${PORT}`));
